export const LOAD_USER_ORDERS = 'order/LOAD_USER_ORDERS';
export const LOAD_USER_ORDERS_SUCCESS = 'order/LOAD_USER_ORDERS_SUCCESS';
export const LOAD_USER_ORDERS_FAILED = 'order/LOAD_USER_ORDERS_FAILED';

export default {
  LOAD_USER_ORDERS,
  LOAD_USER_ORDERS_SUCCESS,
  LOAD_USER_ORDERS_FAILED,
};
